### ISSUE TITLE
 TypeError "seneca.make$ is not a function" in transport-utils.js

### ISSUE THREAD

**Issue by dynobo** [senecajs/seneca-transport#100] opened 2016-05-14 20:59 UTC
I'm, getting the error below on a simple rest call to seneca api. For me, it seems to be related to [this recent change in Seneca](https://github.com/senecajs/seneca/issues/383).

```
2016-05-14T20:46:45.585Z ksrwwntvzf0a/1463258804974/2253/- INFO	client	{type:tcp,port:4007,pin:service:monitor}
/home/sam-dev/Sam/app/node_modules/seneca-transport/lib/transport-utils.js:492
      raw[key] = seneca.make$(value)
                        ^

TypeError: seneca.make$ is not a function
    at /home/sam-dev/Sam/app/node_modules/seneca-transport/lib/transport-utils.js:492:25
    at /home/sam-dev/Sam/app/node_modules/seneca-transport/node_modules/lodash/lodash.js:4127:15
    at baseForOwn (/home/sam-dev/Sam/app/node_modules/seneca-transport/node_modules/lodash/lodash.js:2639:24)
    at /home/sam-dev/Sam/app/node_modules/seneca-transport/node_modules/lodash/lodash.js:4096:18
    at Function.forEach (/home/sam-dev/Sam/app/node_modules/seneca-transport/node_modules/lodash/lodash.js:7768:11)
    at internals.Utils.handle_entity (/home/sam-dev/Sam/app/node_modules/seneca-transport/lib/transport-utils.js:490:5)
    at internals.Utils.handle_response (/home/sam-dev/Sam/app/node_modules/seneca-transport/lib/transport-utils.js:82:19)
    at Duplex.messager._write (/home/sam-dev/Sam/app/node_modules/seneca-transport/lib/tcp.js:185:19)
    at doWrite (_stream_writable.js:300:12)
    at writeOrBuffer (_stream_writable.js:286:5)
```

I have these seneca packages installed:
```
    "seneca": "^2.0.1",
    "seneca-entity": "0.0.1",
    "seneca-mongo-store": "^0.2.0",
```

**Comment by mcdonnelldean** [comment] 2016-05-14 21:24
Could you show the code you are using to start Seneca?

**Comment by dynobo** [comment] 2016-05-14 21:28
This is the code that starts seneca and where the error is thrown:
```
require('../shared/logger');

var seneca = require('seneca')()
    .use('api')
    .client({
        type: 'tcp',
        port: '4001',
        pin: 'thing:rollershutter'
    })
    .client({
        type: 'tcp',
        port: '4002',
        pin: 'service:scheduler'
    })
    .client({
        type: 'tcp',
        port: '4003',
        pin: 'thing:temperature'
    })
    .client({
        type: 'tcp',
        port: '4004',
        pin: 'thing:cdlight'
    })
    .client({
        type: 'tcp',
        port: '4005',
        pin: 'service:speak'
    })
    .client({
        type: 'tcp',
        port: '4006',
        pin: 'thing:powerswitch'
    })
    .client({
        type: 'tcp',
        port: '4007',
        pin: 'service:monitor'
    });

var app = require('express')()
    .use(function(req, res, next) {
        res.setHeader('Access-Control-Allow-Headers', 'accept, authorization, content-type, x-requested-with');
        res.setHeader('Access-Control-Allow-Methods', 'GET,HEAD,PUT,PATCH,POST,DELETE');
        res.setHeader('Access-Control-Allow-Origin', '*');
        next();
    })
    .use(require('body-parser').json())
    .use(seneca.export('web'))
    .listen(3000);
```

**Comment by dynobo** [comment] 2016-05-15 00:19
Here is my api-plugin:
```
module.exports = function api(options) {

   // ROLLERSHUTTER
   // ***********************
   var valid_ops_rollershutter = {
      open: 'open',
      close: 'close',
      stop: 'stop',
      heartbeat: 'heartbeat'
   };

   this.add('role:api,path:rollershutter', function(msg, respond) {
      this.act('thing:rollershutter', {
         cmd: valid_ops_rollershutter[msg.command],
         windowCode: msg.windowCode
      }, respond);
   });

   // SCHEDULE
   // ***********************
   var valid_ops_scheduler = {
      set: 'set',
      get: 'get',
      list: 'list',
      actions: 'actions',
      delete: 'delete',
      heartbeat: 'heartbeat'
   };

   this.add('role:api,path:scheduler', function(msg, respond) {
      this.act('service:scheduler', {
         cmd: valid_ops_scheduler[msg.command],
         taskId: msg.taskId,
         cron: msg.cron,
         execute: msg.execute
      }, respond);
   });

   // TEMPERATURE
   // ***********************
   var valid_ops_temperature = {
      get: 'get',
      measure: 'measure',
      heartbeat: 'heartbeat'
   };

   this.add('role:api,path:temperature', function(msg, respond) {
      this.act('thing:temperature', {
         cmd: valid_ops_temperature[msg.command],
         days: msg.days
      }, respond);
   });

   // CDLIGHT
   // ***********************
   var valid_ops_cdlight = {
      send: 'send',
      heartbeat: 'heartbeat'
   };

   this.add('role:api,path:cdlight', function(msg, respond) {
      this.act('thing:cdlight', {
         cmd: valid_ops_cdlight[msg.command],
         irCode: msg.irCode
      }, respond);
   });

   // SPEAK
   // ***********************
   var valid_ops_speak = {
      say: 'say',
      quote: 'quote',
      heartbeat: 'heartbeat'
   };

   this.add('role:api,path:speak', function(msg, respond) {
      this.act('service:speak', {
         cmd: valid_ops_speak[msg.command],
         message: msg.message,
         collection: msg.collection
      }, respond);
   });

   // powerswitch
   // ***********************
   var valid_ops_powerswitch = {
      on: 'on',
      off: 'off',
      state: 'state',
      heartbeat: 'heartbeat'           
   };

   this.add('role:api,path:powerswitch', function(msg, respond) {
      this.act('thing:powerswitch', {
         cmd: valid_ops_powerswitch[msg.command],
         switchId: msg.switchId,
      }, respond);
   });

   // monitor
   // ***********************
   var valid_ops_monitor = {
      microservices: 'microservices',
   };

   this.add('role:api,path:monitor', function(msg, respond) {
      this.act('service:monitor', {
         cmd: valid_ops_monitor[msg.command],
         serviceId: msg.serviceId,
      }, respond);
   });

   // INIT the api and map
   // ***********************
   this.add('init:api', function(msg, respond) {
      this.act('role:web', {
         use: {
            prefix: '/api',
            pin: 'role:api,path:*',
            map: {
               rollershutter: {
                  GET: true,
                  suffix: '/:command'
               },
               scheduler: {
                  GET: true,
                  suffix: '/:command'
               },
               temperature: {
                  GET: true,
                  suffix: '/:command'
               },
               cdlight: {
                  GET: true,
                  suffix: '/:command'
               },
               speak: {
                  GET: true,
                  suffix: '/:command'
               },
               powerswitch: {
                  GET: true,
                  suffix: '/:command'
               },
               monitor: {
                  GET: true,
                  suffix: '/:command'
               }
            }
         }
      }, respond);
   });

};
```

**Comment by mcdonnelldean** [comment] 2016-05-15 08:47
@dynobo So it looks like a regression here. There is a passthrough function that ensures entities are correctly made when they pass over the network. 2.x was supposed to remove entities as a default requirement so this logic needs to be rethunk.

Logic in question, 
https://github.com/senecajs/seneca-transport/blob/master/lib/transport-utils.js#L476-L497

In order to fix this properly I think it's best to find out what messages are being treated as entities since it doesn't look like you are using any entity logic specifically. In your working code could you add, `console.log(value)` right above the line below?

https://github.com/senecajs/seneca-transport/blob/master/lib/transport-utils.js#L492

This should dump out any message that is marked as $entity and help me figure out the best way to proceed. Feel free to replace any sensitive data with `''` I'm mostly interested in the pattern and any auto generated data added by Seneca.

As a work around, if you `npm install --save seneca-entity` and then add the following modification to your code from above.

```js
require('../shared/logger');

var seneca = require('seneca')()
    .use('entity')
    .use('api')

...
```

This will load the entity logic and an in mem store, that should get around the issue until we patch it.

**Comment by mcdonnelldean** [comment] 2016-05-15 08:51
@rjrodger This may be the reason entities wasn't fully removed from core. We need to figure out where this should live. This needs thought because we could have entities coming in to instances that don't need to do anything with them (likely in cases where folks don't clean their message before sending). There may also be core messages floating about that are entities themselves.

**Comment by mcollina** [comment] 2016-05-15 17:01
I've hit this problem in https://github.com/senecajs/seneca/pull/402, and that is why I had to "fix" all the entity tests.

**Comment by dynobo** [comment] 2016-05-15 17:51
@mcdonnelldean I added the console.log(value), my output now is:
```
[2016-05-15 19:42:51] [LOG]   { 'entity$': '-/-/powerswitch', on: true, id: 'powerswitch_1' }
/home/pi/Sam/app/node_modules/seneca-transport/lib/transport-utils.js:493
      raw[key] = seneca.make$(value)
                        ^

TypeError: seneca.make$ is not a function
...
```

So "value" is a call to another of my microservices.

Adding .use('entity') fixed it for me. Still I'm not sure, whats happening there, because I don't use the store in this service... ;-)

**Comment by sax1johno** [comment] 2016-06-02 16:38
Just as a note, I had this problem while running tests using seneca.client.  I already had seneca.use('entity') on my main service but my tests were still failing.

You also have to add seneca.client().use('entity') as well if you're using the client syntax.

**Comment by mcdonnelldean** [comment] 2016-06-28 13:23
@sax1johno Good spot! I have also removed entities correctly from Seneca and transport too so they load in an out as expected. Should land soon.

**Closed by mcdonnelldean** 2016-06-28 13:23 UTC
Labels: bug, investigate
